### ISSUE TITLE
[bug] PrepareNewVersion for coredocument should not overwrite existing collaborators, it should merge

### ISSUE THREAD

**Issue by vimukthi-git** [centrifuge/go-centrifuge#412] opened 2018-11-07 10:19 UTC
@mikiquantum

**Comment by mikiquantum** [comment] 2018-11-07 12:09
This is not a bug, it was the initial intention to overwrite collaborators with update. We knew it was a simplistic approach and I agree we should merge.
In addition, this is brings up a more complex topic which is ACLs per document basis, who modified it last (keeping the client that modifies the document in the `[0]` position)

**Comment by vedhavyas** [comment] 2018-11-07 12:58
Not sure I agree with merging the collaborators from the previous version. Each version of the document will have its own ACLs as per the collaborators present in the version. Merging these will cause additional complexity of managing ACLs from one version to another

**Comment by vimukthi-git** [comment] 2018-11-07 13:07
having an ACL or not is a separate question we might not even get to in the near future. This is a bug because clients of the API shouldn't have to handle the complexity of merging collaborators, or worst case removing all the collaborators without knowing, thats the implementation right now if you don't send the collaborators. Updates to documents shouldn't require clients to always send the collaborators (or the clients of the API managing ACLs :P).

Please let's fix this now, and discuss about ACLs later. I made a hack fix on Hokodo app side to address missing collaborators. Still it double appends the updating node.

**Comment by lucasvo** [comment] 2018-11-08 14:50
We can't fix this because we would be unable to remove a collaborator if we would always merge. I think for now the client should just maintain the list of collaborators. I'm closing this for now.

**Comment by lucasvo** [comment] 2018-11-08 14:50
When we tackle permisisons/ACLs we can talk about this again.

**Closed by lucasvo** 2018-11-08 14:50 UTC

**Comment by vimukthi-git** [comment] 2018-11-08 15:02
There is a reason I created this, at least the double appends of sending node should be fixed. otherwise the clients have to always filter out the cent id of the sending node when updating a document.
