### ISSUE TITLE
job id displayed as document id

### ISSUE THREAD

**Issue by Przemek-Win** [centrifuge/go-centrifuge#1134] opened 2019-06-18 18:17 UTC
#### Expected behaviour 
Webhook returns the same document id as response from POST request.

#### Actual behaviour
Webhook returns document id after creating invoice, which is in fact job id. It is not coherent with document id received as response to post request to the node for creating invoice.

#### Steps to reproduce the behaviour
Create new invoice with post request and check the webhook.

**Comment by vedhavyas** [comment] 2019-07-22 12:17
Duplicate of #1057

**Closed by vedhavyas** 2019-07-22 12:17 UTC
Labels: bug
