### ISSUE TITLE
Return TxHash in POST response 

### ISSUE THREAD

**Issue by Remi-Tuy** [centrifuge/go-centrifuge#735] opened 2019-02-08 10:50 UTC
Any post (anchor document or mint) currently returns the centrifuge transaction id in the following format.

"transaction_id":"b1f73ce5-8774-4840-949d-f7d2d4f805e3"

Would be more then useful to add to the reponse messages the onchain TxHash.

***Current response format***
**/invoice**
```
{
  "header": {
    "document_id": "string",
    "version_id": "string",
    "state": "string",
    "collaborators": [
      "string"
    ],
    "transaction_id": "string"
  },
  "data": {
[...]
  }
}
```
**/token/mint**
```
{
  "header": {
    "transaction_id": "string"
  },
  "token_id": "string"
}
```
***Proposed format***
**/invoice**
```
{
  "header": {
    "document_id": "string",
    "version_id": "string",
    "state": "string",
    "collaborators": [
      "string"
    ],
    "transaction_id": "string",
    "transaction_hash": "string"
  },
  "data": {
[...]
  }
}
```
**/token/mint**
```
{
  "header": {
    "transaction_id": "string"
    "transaction_hash": "string"
  },
  "token_id": "string"
}
```

**Comment by lucasvo** [comment] 2019-04-02 12:02
This is a duplicate of #490

**Closed by lucasvo** 2019-04-02 12:02 UTC
